#!/usr/bin/env bash

user=''

# Parse command-line arguments
args=( "$@" )

for ((i = 0; i < $#; i++)); do
  case "${args[$(($i))]}" in
    -h | --help )
      echo ""
      echo -e $'A bash script for setting up the workflow generator utility.'
      echo ""
      echo -e $'REQUIRED*'
      echo "-----------------------------------------------------------------"
      echo -e $'\e[32m-f  \e[39mor \e[32m--file\e[39m*   \e[39mThe filepath to the file to read from to generate the config file.'
      echo "-----------------------------------------------------------------"
      echo ""
      echo -e $'\e[35mEXAMPLES\e[39m:'
      echo "./setup.sh -u bobby"
      echo ""
      echo "-----------------------------------------------------------------"
      echo ""
      exit 1;
      ;;
    -u | --user)
      user="${args[$((i+1))]}"
      ;;
    *)
      ;;
  esac
done

# Validate user input
if [ -z "$user" ]; then
  echo -e $'\e[31mERROR\e[37m: You must provide a username using the '-u' or '--user' option.'
  echo -e $'See help: \e[33m./setup.sh -h\e[37m or \e[33m./setup.sh --help\e[37m'
  exit 1
fi

# Generate Makefile
cat <<EOF > Makefile
# Makefile generated by setup.sh

USER=$user
SCRIPT_PATH=/home/\$(USER)/update-from-upstream
BIN_PATH=/usr/bin/update-from-upstream

install:
	mkdir -p \$(SCRIPT_PATH)
	cp update-from-upstream.sh \$(SCRIPT_PATH)/update-from-upstream.sh
	chmod +x \$(SCRIPT_PATH)/update-from-upstream.sh
	sudo ln -sf \$(SCRIPT_PATH)/update-from-upstream.sh \$(BIN_PATH)

uninstall:
	sudo rm -f \$(BIN_PATH)
	rm -rf \$(SCRIPT_PATH)

.PHONY: install uninstall
EOF

echo -e $'\e[32mMakefile has been generated successfully!\e[37m'


